server:
  port: 8081
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/agri
    username: root
    password: 667293abC

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

#mybatis配置
mybatis:
  configuration:
    #下划线至驼峰映射
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.pos125.domain
  mapperLocations: classpath*:mapper/*Mapper.xml